export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const NEW_TRANSACTION = 'NEW_TRANSACTION'
export const FILTER_TRANSACTIONS = 'FILTER_TRANSACTIONS'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
