export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const NEW_TRANSACTION = 'NEW_TRANSACTION'
export const FILTER_BY_MONTH = 'FILTER_BY_MONTH'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
